var canvas=document.getElementById("myCanvas");
var ctx=canvas.getContext("2d");
var color1= "blue";
ctx.beginPath();
ctx.strokeStyle=color1;
ctx.lineWidth=2;
ctx.arc(250,210,40,0,2* Math.PI);
ctx.stroke();
var color2= "yellow";
ctx.beginPath();
ctx.strokeStyle=color2;
ctx.lineWidth=2;
ctx.arc(300,260,40,0,2* Math.PI);
ctx.stroke();
var color3= "black";
ctx.beginPath();
ctx.strokeStyle=color3;
ctx.lineWidth=2;
ctx.arc(350,210,40,0,2* Math.PI);
ctx.stroke();
var color4= "green";
ctx.beginPath();
ctx.strokeStyle=color4;
ctx.lineWidth=2;
ctx.arc(400,260,40,0,2* Math.PI);
ctx.stroke();
var color5= "red";
ctx.beginPath();
ctx.strokeStyle=color5;
ctx.lineWidth=2;
ctx.arc(450,210,40,0,2* Math.PI);
ctx.stroke()